# Generated by Django 4.0.3 on 2022-10-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Cedula', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deuda', models.IntegerField()),
                ('total_cuotas', models.IntegerField()),
                ('banco', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='app.bancos')),
                ('cliente', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.IntegerField()),
                ('cuotas', models.IntegerField()),
                ('banco', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='app.deuda')),
                ('cliente', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
            ],
        ),
    ]
