# Generated by Django 4.0.3 on 2022-10-13 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nombre_bancos_nombreb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='deuda',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app.deuda'),
        ),
    ]
